(function(g){var window=this;var gqa=function(a,b){return g.Ub(a,b)},L5=function(){},hqa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},iqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Ld&&"function"==typeof a.Ld)var c=a.Ld();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=hqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},M5=function(a){g.nn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},N5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.sn(a.l,b,c)},O5=function(a){return(a=g.Lo(a))?new ActiveXObject(a):new XMLHttpRequest},P5=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},jqa=function(a){return"content-type"==a.toLowerCase()},Q5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},kqa=function(a){return g.Ld&&g.nd(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},R5=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},S5=function(a,b){if(a.g){Q5(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},T5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;R5(a);S5(a)},U5=function(a){return a.g?a.g.readyState:0},V5=function(a){if(a.i&&"undefined"!=typeof g.MY)if(a.R[1]&&4==U5(a)&&2==a.getStatus())P5(a,"Local request error detected and ignored");
else if(a.C&&4==U5(a))g.Hg(a.Zv,0,a);else if(a.dispatchEvent("readystatechange"),4==U5(a)){P5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!lqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<U5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";R5(a)}}finally{S5(a)}}},W5=function(a){g.Tf.call(this);
this.headers=new g.bn;this.M=a||null;this.i=!1;this.R=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.C=this.P=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},X5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},mqa=function(a,b){var c=[];
g.Rk(b,function(d){try{var e=g.$o.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Zo(e)&&c.push(d):c.push(d)},a);
return c},nqa=function(a,b){var c=mqa(a,b);
(0,g.y)(c,function(d){g.$o.prototype.remove.call(this,d)},a)},Y5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},oqa=function(a,b){g.$a(a,b)||a.push(b)},Z5=function(a){var b=0,c;
for(c in a)b++;return b},$5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},pqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},qqa=function(a,b,c,d){var e=new g.en(null,void 0);
a&&g.fn(e,a);b&&g.gn(e,b);c&&g.hn(e,c);d&&(e.i=d);return e},a6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return pqa(a)},b6=function(){this.g=[];
this.i=[]},c6=function(a,b){g.eq[a]=!0;
var c=g.cq();c&&c.publish.apply(c,arguments);g.eq[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.bn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",rqa(this,a.capabilities||""),sqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},rqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(gqa,tqa)).forEach(function(c){a.capabilities.add(c)})},sqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},g6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},uqa=function(a){return new e6(a)},h6=function(a){return g.Ka(a)?(0,g.ge)(a,uqa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},vqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.Xa(a,function(c){return f6(c,b)})},n6=function(a){try{var b=(0,g.At)(),c=(0,g.zt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},wqa=function(){var a=(0,g.zt)();
a&&nqa(a,a.g.lf(!0))},o6=function(){var a=g.Ct("yt-remote-connected-devices")||[];
g.qb(a);return a},xqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},p6=function(a){g.Bt("yt-remote-connected-devices",a,86400)},r6=function(){if(q6)return q6;
var a=g.Ct("yt-remote-device-id");a||(a=k6(),g.Bt("yt-remote-device-id",a,31536E3));for(var b=o6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return q6=d},s6=function(){var a=o6(),b=r6();
g.$a(a,b);g.Dt()&&g.sb(a,b);a=xqa(a);if(0==a.length)try{g.Fs("remote_sid")}catch(c){}else try{g.Es("remote_sid",a.join(","),-1)}catch(c){}},t6=function(){return g.Ct("yt-remote-session-browser-channel")},u6=function(){return g.Ct("yt-remote-local-screens")||[]},v6=function(){g.Bt("yt-remote-lounge-token-expiration",!0,86400)},yqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(u6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.lj)(c,function(d){return!g.$a(b,d)})&&v6();
g.Bt("yt-remote-local-screens",a,31536E3)},zqa=function(a,b){g.Bt("yt-remote-session-browser-channel",a);
g.Bt("yt-remote-session-screen-id",b);var c=o6(),d=r6();g.$a(c,d)||c.push(d);p6(c);s6()},w6=function(a){a||(n6("yt-remote-session-screen-id"),n6("yt-remote-session-video-id"));
s6();a=o6();g.db(a,r6());p6(a)},y6=function(){if(!x6){var a=g.jp();
a&&(x6=new g.Uo(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},z6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},A6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},C6=function(a){a.length?B6(a.shift(),function(){C6(a)}):D6()},Aqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},B6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},D6=function(){var a=A6();
a&&a(!1,"No cast extension found")},E6=function(){if(Bqa){var a=2,b=A6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;B6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",D6,c)}},Cqa=function(){E6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);C6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},F6=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Vc=b;this.u=(0,g.x)(this.pD,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},G6=function(){},H6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.ca=new g.tn(this);this.i=new g.Gg;this.i.setInterval(250)},J6=function(a,b,c){a.Wh=1;
a.Yf=M5(b.clone());a.rh=c;a.u=!0;I6(a,null)},K6=function(a,b,c,d,e){a.Wh=1;
a.Yf=M5(b.clone());a.rh=null;a.u=c;e&&(a.Yz=!1);I6(a,d)},I6=function(a,b){a.Gi=(0,g.D)();
L6(a);a.Dg=a.Yf.clone();N5(a.Dg,"t",a.A);a.ll=0;a.tc=a.g.xp(a.g.Uk()?b:null);0<a.Zp&&(a.On=new g.Jl((0,g.x)(a.gB,a,a.tc),a.Zp));a.ca.da(a.tc,"readystatechange",a.eM);var c=a.Yg?g.bc(a.Yg):{};a.rh?(a.vo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Dg,a.vo,a.rh,c)):(a.vo="GET",a.Yz&&!g.Nd&&(c.Connection="close"),a.tc.send(a.Dg,a.vo,null,c));a.g.we(1)},S6=function(a,b,c){for(var d=!0;!a.Ng&&a.ll<c.length;){var e=Dqa(a,c);
if(e==M6){4==b&&(a.pg=4,N6(15),d=!1);break}else if(e==O6){a.pg=4;N6(16);d=!1;break}else P6(a,e)}4==b&&0==c.length&&(a.pg=1,N6(17),d=!1);a.ze=a.ze&&d;d||(Q6(a),R6(a))},Dqa=function(a,b){var c=a.ll,d=b.indexOf("\n",c);
if(-1==d)return M6;c=Number(b.substring(c,d));if(isNaN(c))return O6;d+=1;if(d+c>b.length)return M6;var e=b.substr(d,c);a.ll=d+c;return e},V6=function(a,b){a.Gi=(0,g.D)();
L6(a);var c=b?window.location.hostname:"";a.Dg=a.Yf.clone();g.nn(a.Dg,"DOMAIN",c);g.nn(a.Dg,"t",a.A);try{a.Ee=new ActiveXObject("htmlfile")}catch(n){Q6(a);a.pg=7;N6(22);R6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in T6)k=T6[l];else if(l in U6)k=T6[l]=U6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
T6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ee.open();a.Ee.write(g.Mc(c));a.Ee.close();a.Ee.parentWindow.m=(0,g.x)(a.uL,a);a.Ee.parentWindow.d=(0,g.x)(a.ez,a,!0);a.Ee.parentWindow.rpcClose=(0,g.x)(a.ez,a,!1);c=a.Ee.createElement("DIV");a.Ee.parentWindow.document.body.appendChild(c);d=g.Cc(a.Dg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.we(1)},L6=function(a){a.Ys=(0,g.D)()+a.o;
W6(a,a.o)},W6=function(a,b){if(null!=a.Xi)throw Error("WatchDog timer not null");
a.Xi=X6((0,g.x)(a.EL,a),b)},Y6=function(a){a.Xi&&(g.v.clearTimeout(a.Xi),a.Xi=null)},R6=function(a){a.g.Xv()||a.Ng||a.g.Cn(a)},Q6=function(a){Y6(a);
g.rf(a.On);a.On=null;a.i.stop();g.vn(a.ca);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Ee&&(a.Ee=null)},P6=function(a,b){try{a.g.Yy(a,b),a.g.we(4)}catch(c){}},$6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Z6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){$6(a,b,c,d,f)},f)})}},Z6=function(a,b,c){var d=new Image;
d.onload=function(){try{a7(d),c(!0)}catch(e){}};
d.onerror=function(){try{a7(d),c(!1)}catch(e){}};
d.onabort=function(){try{a7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{a7(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
$5(d,a)},a7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},b7=function(a){this.g=a;
this.i=new G6},d7=function(a){var b=c7(a.g,a.kj,"/mail/images/cleardot.gif");
M5(b);$6(b.toString(),5E3,(0,g.x)(a.wC,a),3,2E3);a.we(1)},f7=function(a){var b=a.g.F;
if(null!=b)N6(5),b?(N6(11),e7(a.g,a,!1)):(N6(12),e7(a.g,a,!0));else if(a.Fd=new H6(a,void 0,void 0,void 0),a.Fd.Yg=a.Xp,b=a.g,b=c7(b,b.Uk()?a.Rj:null,a.Yp),N6(5),!g.Ld||g.od(10))N5(b,"TYPE","xmlhttp"),K6(a.Fd,b,!1,a.Rj,!1);else{N5(b,"TYPE","html");var c=a.Fd;a=!!a.Rj;c.Wh=3;c.Yf=M5(b.clone());V6(c,a)}},g7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new G6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Eqa=function(a,b){this.g=a;
this.map=b;this.context=null},h7=function(a){g.tf.call(this,"statevent",a)},i7=function(a,b){g.tf.call(this,"timingevent",a);
this.size=b},j7=function(a){g.tf.call(this,"serverreachability",a)},n7=function(a){k7(a);
if(3==a.g){var b=a.zk++,c=a.lm.clone();g.nn(c,"SID",a.l);g.nn(c,"RID",b);g.nn(c,"TYPE","terminate");l7(a,c);b=new H6(a,a.l,b,void 0);b.Wh=2;b.Yf=M5(c.clone());$5(new Image,b.Yf.toString());b.Gi=(0,g.D)();L6(b)}m7(a)},p7=function(a){a.OC(1,0);
a.lm=c7(a,null,a.Wp);o7(a)},k7=function(a){a.fg&&(a.fg.abort(),a.fg=null);
a.Vb&&(a.Vb.cancel(),a.Vb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);q7(a);a.Bd&&(a.Bd.cancel(),a.Bd=null);a.mg&&(g.v.clearTimeout(a.mg),a.mg=null)},r7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Eqa(a.KH++,b));2!=a.g&&3!=a.g||o7(a)},o7=function(a){a.Bd||a.mg||(a.mg=X6((0,g.x)(a.dz,a),0),a.Ph=0)},u7=function(a,b){if(1==a.g){if(!b){a.zk=Math.floor(1E5*Math.random());
var c=a.zk++,d=new H6(a,"",c,void 0);d.Yg=null;var e=s7(a),f=a.lm.clone();g.nn(f,"RID",c);g.nn(f,"CVER","1");l7(a,f);J6(d,f,e);a.Bd=d;a.g=2}}else 3==a.g&&(b?t7(a,b):0==a.i.length||a.Bd||t7(a))},t7=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.zk-1;var d=s7(a)}else c=b.C,d=b.rh;else c=a.zk++,d=s7(a);var e=a.lm.clone();g.nn(e,"SID",a.l);g.nn(e,"RID",c);g.nn(e,"AID",a.ji);l7(a,e);c=new H6(a,a.l,c,a.Ph+1);c.Yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Bd=c;J6(c,e,d)},l7=function(a,b){if(a.Tc){var c=a.Tc.Av();
c&&g.Kb(c,function(d,e){g.nn(b,e,d)})}},s7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},v7=function(a){a.Vb||a.nf||(a.C=1,a.nf=X6((0,g.x)(a.cz,a),0),a.Ih=0)},x7=function(a){if(a.Vb||a.nf||3<=a.Ih)return!1;
a.C++;a.nf=X6((0,g.x)(a.cz,a),w7(a,a.Ih));a.Ih++;return!0},e7=function(a,b,c){a.so=c;
a.Le=b.Af;a.A||p7(a)},q7=function(a){null!=a.Sg&&(g.v.clearTimeout(a.Sg),a.Sg=null)},w7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},z7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.IM,a);c||(c=new g.en("//www.google.com/images/cleardot.gif"),M5(c));Z6(c.toString(),1E4,d)}else N6(2);y7(a,b)},y7=function(a,b){a.g=0;
a.Tc&&a.Tc.Cu(b);m7(a);k7(a)},m7=function(a){a.g=0;
a.Le=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.jp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Tc.jp(b)}},c7=function(a,b,c){var d=g.on(c);
if(""!=d.g)b&&g.gn(d,b+"."+d.g),g.hn(d,d.u);else{var e=window.location;d=qqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.zj&&g.Kb(a.zj,function(f,k){g.nn(d,k,f)});
g.nn(d,"VER",a.Og);l7(a,d);return d},X6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},N6=function(a){A7.dispatchEvent(new h7(A7,a))},B7=function(){},Fqa=function(a,b){this.action=a;
this.params=b||{}},C7=function(a,b){g.A.call(this);
this.g=new g.J(this.mL,0,this);g.B(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},D7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.To;this.i=new C7(this.nM,this);this.g=null;this.gb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},Gqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.so,sessionId:a.g.l,arrayId:a.g.ji}},E7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&u7(a.g),n7(a.g));a.D=0},F7=function(a){return!!a.g&&3==a.g.g},Hqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Tg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},H7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),ke:g.Qa(a.u,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Xq(b,a)},Iqa=function(){var a=J7;
K7();L7.push(a);M7(L7)},N7=function(a,b){K7();
var c=L7,d=Jqa(a,String(b));0==c.length?Kqa(d):(M7(c),(0,g.y)(c,function(e){e(d)}))},K7=function(){L7||(L7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",L7,void 0))},Kqa=function(a){var b=(O7+1)%50;
O7=b;P7[b]=a;Q7||(Q7=49==b)},M7=function(a){var b=P7;
if(b[0]){var c=O7,d=Q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
P7=Array(50);O7=-1;Q7=!1}},Jqa=function(a,b){var c=((0,g.D)()-Lqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},R7=function(a){g.N.call(this);
this.C=a;this.g=[]},S7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Mqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=S7(a,b[d])||c;return c},Nqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},T7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},V7=function(a){R7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;U7(this);this.info("Initializing with "+j6(this.g))},Oqa=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=H7(a.l,"/pairing/get_lounge_token_batch");
I7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.zD,a),(0,g.x)(a.yD,a))}},U7=function(a){var b=h6(u6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return Mqa(a,b)},W7=function(a,b){yqa((0,g.ge)(a.g,g6));
b&&v6()},Y7=function(a,b){g.N.call(this);
this.A=b;var c=g.Ct("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;X7("Initialized with "+g.Lg(this.g))},Pqa=function(a,b,c){var d=H7(a.u,"/pairing/get_screen_availability");
I7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},Z7=function(a,b){a:if(Z5(b)!=Z5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(X7("Updated online screens: "+g.Lg(a.g)),a.g=b,a.N("screenChange"));Qqa(a)},$7=function(a){isNaN(a.l)||g.bq(a.l);
a.l=g.$p((0,g.x)(a.es,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},X7=function(a){N7("OnlineScreenService",a)},Rqa=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},Qqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Bt("yt-remote-online-screen-ids",a.join(","),60):n6("yt-remote-online-screen-ids")},a8=function(a){R7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Sqa(this)},Uqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Md();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=b8(a,k);Pqa(a.i,l,function(m){e(m?l:null)})}else c?Tqa(a,c,(0,g.x)(function(m){var n=b8(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Pqa(this.i,n,function(q){e(q?n:null)})},a),f):e(null)},Vqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Tqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Xq(H7(a.A,"/pairing/get_lounge_token_batch"),e)},Wqa=function(a){a.g=a.l.Md();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.g))},Sqa=function(a){c8(a);
a.l=new V7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.HD,a));Wqa(a);a.o=h6(g.Ct("yt-remote-automatic-screen-cache")||[]);c8(a);a.info("Initializing automatic screens: "+j6(a.o));a.i=new Y7(a.A,(0,g.x)(a.Md,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},b8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Bt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,g6)));c8(a);a.u[b.uuid]=b.id;g.Bt("yt-remote-device-id-map",a.u,31536E3);return b},c8=function(a){a.u=g.Ct("yt-remote-device-id-map")||{}},d8=function(a,b,c){g.N.call(this);
this.R=c;this.F=a;this.i=b;this.l=null},e8=function(a,b){N7(a.R,b)},f8=function(a,b){d8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.pN,this);this.u=(0,g.x)(this.PL,this);this.o=g.$p((0,g.x)(function(){Xqa(this,null)},this),12E4)},Yqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){e8(this,"Failed to send message: getMdxSessionStatus.")},a)):e8(a,"Sending yt message without session: "+g.Lg(b))},Xqa=function(a,b){g.bq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.En,a),d=(0,g.x)(a.Qd,a);a.Pv(b,c,d,5)}}else a.Qd(Error("Waiting for session status timed out."))},g8=function(a,b,c){d8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ha;this.A=NaN;this.I=(0,g.x)(this.sN,this);this.g=g.Ha},Zqa=function(a){a.g=a.F.lB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.En(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Qd(b)},a))},$qa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}y6()&&(b.env_useStageMdx=1);return g.bh(b)},h8=function(a,b){d8.call(this,a,b,"ManualSession");
this.g=g.$p((0,g.x)(this.li,this,null),150)},i8=function(a,b,c,d){g.N.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.vK,this)},ara=function(a,b){return b?g.Xa(a.l,function(c){return f6(b,c.label)},a):null},j8=function(a){N7("Controller",a)},J7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},k8=function(a){return a.u||!!a.l.length||!!a.g},l8=function(a,b,c){b!=a.g&&(g.rf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.bz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.N("yt-remote-cast2-session-change",null))},bra=function(a){var b=a.i.kB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=ara(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},hra=function(a,b,c,d,e,f,k){cra()?dra(b,e,f,k)&&(n8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?era(a,c):(window.__onGCastApiAvailable=function(l,m){l?era(a,c):(o8("Failed to load cast API: "+m),p8(!1),n8(!1),n6("yt-remote-cast-available"),n6("yt-remote-cast-receiver"),fra(),c(!1))},d?g.mq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Cqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?D6():(E6(),C6(gra.map(Aqa))))):m8("Cannot initialize because not running Chrome")},fra=function(){m8("dispose");
var a=q8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);ira(!1);g.hq(r8);r8.length=0},s8=function(){return!!g.Ct("yt-remote-cast-installed")},jra=function(){var a=g.Ct("yt-remote-cast-receiver");
return a?a.friendlyName:null},kra=function(){m8("clearCurrentReceiver");
n6("yt-remote-cast-receiver")},lra=function(){return s8()?q8()?q8().getCastSession():(o8("getCastSelector: Cast is not initialized."),null):(o8("getCastSelector: Cast API is not installed!"),null)},u8=function(){s8()?q8()?t8()?(m8("Requesting cast selector."),q8().requestSession()):(m8("Wait for cast API to be ready to request the session."),r8.push(g.gq("yt-remote-cast2-api-ready",u8))):o8("requestCastSelector: Cast is not initialized."):o8("requestCastSelector: Cast API is not installed!")},v8=
function(a,b){t8()?q8().setConnectedScreenStatus(a,b):o8("setConnectedScreenStatus called before ready.")},cra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.jx||a},mra=function(a,b){q8().init(a,b)},dra=function(a,b,c,d){var e=!1;
q8()||(a=new i8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Bt("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){m8("onReceiverSelected: "+f.friendlyName);
g.Bt("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){m8("onReceiverResumed: "+f.friendlyName);
g.Bt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){m8("onSessionChange: "+i6(f));
f||n6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
m8("cloudview.createSingleton_: "+e);return e},q8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},era=function(a,b){p8(!0);
n8(!1);mra(a,function(c){c?(ira(!0),g.jq("yt-remote-cast2-api-ready")):(o8("Failed to initialize cast API."),p8(!1),n6("yt-remote-cast-available"),n6("yt-remote-cast-receiver"),fra());b(c)})},m8=function(a){N7("cloudview",a)},o8=function(a){N7("cloudview",a)},p8=function(a){m8("setCastInstalled_ "+a);
g.Bt("yt-remote-cast-installed",a)},t8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},ira=function(a){m8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},n8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},w8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Me=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},x8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Me=!1;a.hasNext=!1;a.C=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},y8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},z8=function(a,b){a.C=b;
a.A=(0,g.D)()},A8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},B8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&x8(a)},C8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Me;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},E8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new b6;this.l=this.i=null;this.F=(0,g.x)(this.sI,this);this.C=(0,g.x)(this.Ck,this);this.D=(0,g.x)(this.rI,this);this.H=(0,g.x)(this.GI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.gt,this),nra(this))):c=3;0!=c&&(b?this.gt(c):g.$p((0,g.x)(function(){this.gt(c)},this),0));
var d=lra();d&&D8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},F8=function(a){return new w8(a.o.getPlayerContextData())},nra=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.sK,b),this))},a)},ora=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},G8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},I8=function(a,b,c){var d=F8(a);
z8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.o.sendMessage(b,c)},H8=function(a,b){ora(a);
a.o.setPlayerContextData(C8(b));nra(a)},D8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ck(null));
a.l=b;a.l&&(N7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ck(a.l.media[0]))},pra=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=F8(a);b.contentId!=d.videoId&&N7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;z8(d,a.i.getEstimatedTime());H8(a,d)}else N7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.x)(function(d){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.R=[];this.o=this.A=this.l=this.Oa=this.g=null;this.P=a;this.R.push(g.fs(window,"beforeunload",(0,g.x)(this.sD,this)));this.i=[];this.Oa=new w8;this.M=b.id;this.g=qra(this,c);this.g.subscribe("handlerOpened",this.wI,this);this.g.subscribe("handlerClosed",this.tI,this);this.g.subscribe("handlerError",this.uI,this);this.g.subscribe("handlerMessage",this.vI,this);Hqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.Dt()&&g.Bt("yt-remote-session-video-id",d)},this)},M8=function(a){N7("conn",a)},qra=function(a,b){return new D7(H7(a.P,"/bc"),b)},N8=function(a,b){a.N("proxyStateChange",b)},rra=function(a){a.u=g.$p((0,g.x)(function(){M8("Connecting timeout");
this.Mh(1)},a),2E4)},O8=function(a){g.bq(a.u);
a.u=NaN},P8=function(a){g.bq(a.H);
a.H=NaN},sra=function(a){Q8(a);
a.F=g.$p((0,g.x)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.bq(a.F);
a.F=NaN},ura=function(a,b){b&&(O8(a),P8(a));
b==(F7(a.g)&&isNaN(a.u))?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.Nv()&&a.Oa.reset(),N8(a,1),R8(a,"getNowPlaying"),tra(a)):a.Mh(1)},vra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Xb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},wra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;B8(a.Oa,c,d);a.N("remoteQueueChange")},yra=function(a,b){b.params=b.params||{};
wra(a,b);xra(a,b);a.N("autoplayDismissed")},xra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
z8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?sra(a):Q8(a);a.N("remotePlayerChange")},zra=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);z8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Ara=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Bra=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Cra=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Me="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},tra=function(a){g.bq(a.D);
a.D=g.$p((0,g.x)(a.Mh,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Lg(c)):M8("Sending: action="+b);
a.g.sendMessage(b,c)},S8=function(a){R7.call(this,"ScreenServiceProxy");
this.Uc=a;this.i=[];this.i.push(this.Uc.$_s("screenChange",(0,g.x)(this.mN,this)));this.i.push(this.Uc.$_s("onlineScreenChange",(0,g.x)(this.XJ,this)))},Hra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Sp("MDX_CONFIG")||b;wqa();s6();T8||(T8=new G7(b?b.loungeApiHost:void 0),y6()&&(T8.g="/api/loungedev"));U8||(U8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));Dra();var c=V8();if(!c){var d=new a8(T8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);hra(a,d,function(m){m?W8()&&v8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Lg(b)),Y8.push(g.gq("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),Y8.push(g.gq("yt-remote-cast2-receiver-selected",function(){Z8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.gq("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.gq("yt-remote-cast2-session-change",Era)),Y8.push(g.gq("yt-remote-connection-change",function(m){m?v8(W8(),"YouTube TV"):$8()||(v8(null,null),kra())})),a=a9(),b.isAuto&&(a.id+="#dial"),g.Oq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),X8(" -- with channel params: "+
g.Lg(a)),Fra(a),c.start(),W8()||Gra())},Jra=function(){var a=Ira();
s8()&&g.Ct("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Ira=function(){var a=V8().Uc.$_gos();
var b=b9();b&&c9()&&(l6(a,b)||a.push(b));return vqa(a)},d9=function(){var a=Kra();
!a&&s8()&&jra()&&(a={key:"cast-selector-receiver",name:jra()});return a},Kra=function(){var a=Ira(),b=b9();
b||(b=$8());return g.Xa(a,function(c){return b&&f6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Md();return m6(b,a)},Era=function(a){X8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=b9();b&&b.id==a.id?v8(b.id,"YouTube TV"):(b&&e9(),f9(a,1))}else c9()&&e9()},e9=function(){t8()?q8().stopSession():o8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),g9(null))},h9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){N7("remote",a)},V8=function(){if(!i9){var a=g.w("yt.mdx.remote.screenService_");
i9=a?new S8(a):null}return i9},W8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Lra=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Mra=function(){return g.w("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.w("yt.mdx.remote.connection_")},g9=function(a){var b=c9();
Z8(null);a||Lra("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&((0,g.y)(U8,function(c){c(a)}),U8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},$8=function(){var a=g.Dt();
if(!a)return null;var b=V8().Md();return m6(b,a)},f9=function(a,b){b9()&&b9();
if(j9)k9=a;else{Lra(a.id);var c=new L8(T8,a,a9());c.connect(b,Mra());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){c9()&&g9(null)});
g9(c)}},Gra=function(){var a=$8();
a?(X8("Resume connection to: "+i6(a)),f9(a,0)):(w6(),kra(),X8("Skipping connecting because no session screen found."))},Dra=function(){var a=a9();
if(g.Xb(a)){a=r6();var b=g.Ct("yt-remote-session-name")||"",c=g.Ct("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Fra=function(a){a?(g.Bt("yt-remote-session-app",a.app),g.Bt("yt-remote-session-name",a.name)):(n6("yt-remote-session-app"),n6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},l9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Ps(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.rJ);this.l.K(b,"captionschanged",this.qI);this.l.K(b,"captionssettingschanged",this.yA);this.l.K(b,"videoplayerreset",this.Fn);this.l.K(b,"mdxautoplaycancel",this.vC);this.P=this.l.K(b,"onVolumeChange",this.My);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Xy,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.Fn,this);c.subscribe("autoplayUpNext",this.By,
this);c.subscribe("previousNextChange",this.Uy,this);c.subscribe("nowAutoplaying",this.Qy,this);c.subscribe("autoplayDismissed",this.Ay,this);this.suggestion=null;this.F=new g.GC(64);this.o=new g.J(this.wA,500,this);g.B(this,this.o);this.A=new g.J(this.xA,1E3,this);g.B(this,this.A);this.I=new F6(this.SM,0,this);g.B(this,this.I);this.C={};this.R=new g.J(this.YA,1E3,this);g.B(this,this.R);this.H=new g.Jl(this.NF,1E3,this);g.B(this,this.H);this.M=g.Ha;this.yA();this.Fn();this.Ek()},m9=function(a,b){a.u.Lc(b,
a.i.getVideoData().lengthSeconds)},Nra=function(a){m9(a,0);
a.o.stop();n9(a,new g.GC(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.lA(a.i.getVideoData(1).videoId,c);a.C=F8(a.g).g}},q9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ef,Y5(c));n9(a,new g.GC(1))},Ora=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{RQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},o9=function(a){return F8(a.g).videoId==a.i.getVideoData(1).videoId},n9=function(a,b){a.A.stop();
var c=a.F;if(!g.MC(c,b)){var d=g.S(b,2);d!=g.S(a.F,2)&&g.DK(a.i,d);a.F=b;Pra(a.u,c,b)}},r9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",V:"You're signed out"},{B:"div",G:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.l=new g.wQ(this,250);g.B(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},s9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.LP()]},{B:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.wQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);Qra(this,g.zK(a))},Qra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.KN("Error on $RECEIVER_NAME",c):g.NC(b)||g.S(b,4)?g.KN("Playing on $RECEIVER_NAME",c):g.KN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.hU.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},u9=function(a){g.bL.call(this,a);
this.i={key:k6(),name:"This computer"};this.u=null;this.o=[];this.F=this.g=null;this.C=[this.i];this.l=this.i;this.mk=new g.GC(64);this.I=0;this.Rm=-1;if(!g.oz(g.X(this.player))){a=this.player;var b=g.AD(a);b&&(b=b.ln())&&(b=new t9(a,b),g.B(this,b));b=new s9(a);g.B(this,b);g.OK(a,b.element,4);this.H=new r9;g.B(this,this.H);g.OK(a,this.H.element,4);this.D=!!$8()}this.A=null},v9=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},Pra=function(a,b,c){a.mk=c;
a.player.N("presentingplayerstatechange",new g.RD(c,b))},w9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)e9();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Sp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Sp("SESSION_INDEX")||g.Sp("LOGGED_IN"));c&&!a.D&&(g.NC(g.zK(a.player))||(a.A=(0,g.x)(a.VL,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),c9()||(j9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.sa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ef,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Y5(c))&&(d.locationInfo=c);c=d}else c=null;X8("Connecting to: "+g.Lg(b));"cast-selector-receiver"==b.key?(Z8(c||null),t8()?q8().setLaunchParams(c||null):o8("setLaunchParams called before ready.")):!c&&h9()&&W8()==b.key?c6("yt-remote-connection-change",!0):(e9(),
Z8(c||null),c=V8().Md(),(c=m6(c,b.key))&&f9(c,1))}},lqa=/^https?$/i,Rra=["POST",
"PUT"];g.Sa(W5,g.Tf);g.h=W5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.P=!1;this.i=!0;this.g=this.M?O5(this.M):O5(g.jZ);this.R=this.M?this.M.getOptions():g.jZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.Zv,this);try{L5(P5(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){L5(P5(this,"Error opening Xhr: "+f.message));T5(this,f);return}a=
c||"";var e=this.headers.clone();d&&iqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Ld(),jqa);c=g.v.FormData&&a instanceof g.v.FormData;!g.$a(Rra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{Q5(this),0<this.A&&(this.I=kqa(this.g),L5(P5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.bw,this)):this.F=g.Hg(this.bw,this.A,this)),L5(P5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){L5(P5(this,"Send error: "+f.message)),T5(this,f)}};
g.h.bw=function(){"undefined"!=typeof g.MY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,P5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(P5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),S5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),S5(this,!0));W5.Za.U.call(this)};
g.h.Zv=function(){this.ea()||(this.aa||this.C||this.o?V5(this):this.uK())};
g.h.uK=function(){V5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<U5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var U6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},T6={"'":"\\'"},Sra={};g.h=b6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Sma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var tqa={MN:"atp",dQ:"ska",RP:"que",qP:"mus",cQ:"sus",HO:"dsp",ZP:"seq"};d6.prototype.gg=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var x6,q6="",Bqa=z6("loadCastFramework")||z6("loadCastApplicationFramework"),gra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(F6,g.A);g.h=F6.prototype;g.h.oD=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Vc:this.Aa=g.Hg(this.u,this.Vc)};
g.h.stop=function(){this.Aa&&(g.v.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();F6.Za.U.call(this)};
g.h.pD=function(){this.l?(this.Aa=g.Hg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};G6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
G6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=H6.prototype;g.h.Yg=null;g.h.ze=!1;g.h.Xi=null;g.h.Ys=null;g.h.Gi=null;g.h.Wh=null;g.h.Yf=null;g.h.Dg=null;g.h.rh=null;g.h.tc=null;g.h.ll=0;g.h.Ee=null;g.h.vo=null;g.h.pg=null;g.h.Sj=-1;g.h.Yz=!0;g.h.Ng=!1;g.h.Zp=0;g.h.On=null;var O6={},M6={};g.h=H6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.eM=function(a){a=a.target;var b=this.On;b&&3==U5(a)?b.Oj():this.gB(a)};
g.h.gB=function(a){try{if(a==this.tc)a:{var b=U5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!X5(this.tc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.we(3):this.g.we(2));Y6(this);var e=this.tc.getStatus();this.Sj=e;var f=X5(this.tc);(this.ze=200==e)?(4==b&&Q6(this),this.u?(S6(this,b,f),g.Dh&&this.ze&&3==b&&(this.ca.da(this.i,"tick",this.YL),this.i.start())):P6(this,f),this.ze&&!this.Ng&&(4==b?this.g.Cn(this):(this.ze=
!1,L6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.pg=3,N6(13)):(this.pg=0,N6(14)),Q6(this),R6(this))}}catch(k){this.tc&&X5(this.tc)}finally{}};
g.h.YL=function(){var a=U5(this.tc),b=X5(this.tc);this.ll<b.length&&(Y6(this),S6(this,a,b),this.ze&&4!=a&&L6(this))};
g.h.uL=function(a){X6((0,g.x)(this.tL,this,a),0)};
g.h.tL=function(a){this.Ng||(Y6(this),P6(this,a),L6(this))};
g.h.ez=function(a){X6((0,g.x)(this.sL,this,a),0)};
g.h.sL=function(a){this.Ng||(Q6(this),this.ze=a,this.g.Cn(this),this.g.we(4))};
g.h.cancel=function(){this.Ng=!0;Q6(this)};
g.h.EL=function(){this.Xi=null;var a=(0,g.D)();0<=a-this.Ys?(2!=this.Wh&&this.g.we(3),Q6(this),this.pg=2,N6(18),R6(this)):W6(this,this.Ys-a)};
g.h.getLastError=function(){return this.pg};g.h=b7.prototype;g.h.Xp=null;g.h.Fd=null;g.h.Pn=!1;g.h.Yv=null;g.h.jm=null;g.h.Jq=null;g.h.Yp=null;g.h.fe=null;g.h.Af=-1;g.h.Rj=null;g.h.kj=null;g.h.connect=function(a){this.Yp=a;a=c7(this.g,null,this.Yp);N6(3);this.Yv=(0,g.D)();var b=this.g.D;null!=b?(this.Rj=b[0],(this.kj=b[1])?(this.fe=1,d7(this)):(this.fe=2,f7(this))):(N5(a,"MODE","init"),this.Fd=new H6(this,void 0,void 0,void 0),this.Fd.Yg=this.Xp,K6(this.Fd,a,!1,null,!0),this.fe=0)};
g.h.wC=function(a){if(a)this.fe=2,f7(this);else{N6(4);var b=this.g;b.Le=b.fg.Af;z7(b,9)}a&&this.we(2)};
g.h.xp=function(a){return this.g.xp(a)};
g.h.abort=function(){this.Fd&&(this.Fd.cancel(),this.Fd=null);this.Af=-1};
g.h.Xv=function(){return!1};
g.h.Yy=function(a,b){this.Af=a.Sj;if(0==this.fe)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Le=this.Af;z7(c,2);return}this.Rj=c[0];this.kj=c[1]}else c=this.g,c.Le=this.Af,z7(c,2);else if(2==this.fe)if(this.Pn)N6(7),this.Jq=(0,g.D)();else if("11111"==b){if(N6(6),this.Pn=!0,this.jm=(0,g.D)(),c=this.jm-this.Yv,!g.Ld||g.od(10)||500>c)this.Af=200,this.Fd.cancel(),N6(12),e7(this.g,this,!0)}else N6(8),this.jm=this.Jq=(0,g.D)(),this.Pn=!1};
g.h.Cn=function(){this.Af=this.Fd.Sj;if(this.Fd.ze)0==this.fe?this.kj?(this.fe=1,d7(this)):(this.fe=2,f7(this)):2==this.fe&&((!g.Ld||g.od(10)?!this.Pn:200>this.Jq-this.jm)?(N6(11),e7(this.g,this,!1)):(N6(12),e7(this.g,this,!0)));else{0==this.fe?N6(9):2==this.fe&&N6(10);var a=this.g;this.Fd.getLastError();a.Le=this.Af;z7(a,2)}};
g.h.Uk=function(){return this.g.Uk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.we=function(a){this.g.we(a)};g.h=g7.prototype;g.h.zj=null;g.h.Bd=null;g.h.Vb=null;g.h.Wp=null;g.h.lm=null;g.h.qu=null;g.h.Am=null;g.h.zk=0;g.h.KH=0;g.h.Tc=null;g.h.mg=null;g.h.nf=null;g.h.Sg=null;g.h.fg=null;g.h.so=null;g.h.ji=-1;g.h.Jw=-1;g.h.Le=-1;g.h.Ph=0;g.h.Ih=0;g.h.Og=8;var A7=new g.Tf;g.Sa(h7,g.tf);g.Sa(i7,g.tf);g.Sa(j7,g.tf);g.h=g7.prototype;g.h.connect=function(a,b,c,d,e){N6(0);this.Wp=b;this.zj=c||{};d&&g.Ca(e)&&(this.zj.OSID=d,this.zj.OAID=e);this.A?(X6((0,g.x)(this.Ku,this,a),100),p7(this)):this.Ku(a)};
g.h.Ku=function(a){this.fg=new b7(this);this.fg.Xp=null;this.fg.i=this.u;this.fg.connect(a)};
g.h.Xv=function(){return 0==this.g};
g.h.dz=function(a){this.mg=null;u7(this,a)};
g.h.cz=function(){this.nf=null;this.Vb=new H6(this,this.l,"rpc",this.C);this.Vb.Yg=null;this.Vb.Zp=0;var a=this.qu.clone();g.nn(a,"RID","rpc");g.nn(a,"SID",this.l);g.nn(a,"CI",this.so?"0":"1");g.nn(a,"AID",this.ji);l7(this,a);if(!g.Ld||g.od(10))g.nn(a,"TYPE","xmlhttp"),K6(this.Vb,a,!0,this.Am,!1);else{g.nn(a,"TYPE","html");var b=this.Vb,c=!!this.Am;b.Wh=3;b.Yf=M5(a.clone());V6(b,c)}};
g.h.Yy=function(a,b){if(0!=this.g&&(this.Vb==a||this.Bd==a))if(this.Le=a.Sj,this.Bd==a&&3==this.g)if(7<this.Og){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Vb)if(this.Vb.Gi+3E3<this.Bd.Gi)q7(this),this.Vb.cancel(),this.Vb=null;else break a;x7(this);N6(19)}}else this.Jw=c[1],0<this.Jw-this.ji&&37500>c[2]&&this.so&&0==this.Ih&&!this.Sg&&(this.Sg=X6((0,g.x)(this.mI,this),6E3));else z7(this,11)}else b!=Sra.iO.g&&z7(this,11);else if(this.Vb==a&&
q7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Am=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Tc&&this.Tc.Eu(),this.qu=c7(this,this.Uk()?this.Am:null,this.Wp),v7(this)):"stop"==e[0]&&z7(this,7):3==this.g&&("stop"==e[0]?z7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Du(e),this.Ih=0)}}};
g.h.mI=function(){null!=this.Sg&&(this.Sg=null,this.Vb.cancel(),this.Vb=null,x7(this),N6(20))};
g.h.Cn=function(a){if(this.Vb==a){q7(this);this.Vb=null;var b=2}else if(this.Bd==a)this.Bd=null,b=1;else return;this.Le=a.Sj;if(0!=this.g)if(a.ze)1==b?(b=(0,g.D)()-a.Gi,A7.dispatchEvent(new i7(A7,a.rh?a.rh.length:0,b,this.Ph)),o7(this),this.o.length=0):v7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Le)){if(d=1==b)this.Bd||this.mg||1==this.g||2<=this.Ph?d=!1:(this.mg=X6((0,g.x)(this.dz,this,a),w7(this,this.Ph)),this.Ph++,d=!0);d=!(d||2==b&&x7(this))}if(d)switch(c){case 1:z7(this,
5);break;case 4:z7(this,10);break;case 3:z7(this,6);break;case 7:z7(this,12);break;default:z7(this,2)}}};
g.h.OC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.IM=function(a){a?N6(2):(N6(1),y7(this,8))};
g.h.xp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new W5;a.T=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.we=function(a){A7.dispatchEvent(new j7(A7,a))};
g.h.Uk=function(){return!(!g.Ld||g.od(10))};
g.h=B7.prototype;g.h.Eu=function(){};
g.h.Du=function(){};
g.h.Cu=function(){};
g.h.jp=function(){};
g.h.Av=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(C7,g.A);g.h=C7.prototype;g.h.mL=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.yo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.Sa(D7,B7);g.h=D7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Kf=function(a){return this.l.Zg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.gb||(this.gb=!0,g.rf(this.l),E7(this),g.rf(this.i),this.i=null)};
g.h.ea=function(){return this.gb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new g7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ji):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):F7(this)&&r7(this.g,c)};
g.h.Eu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)r7(this.g,a[b])}this.N("handlerOpened")};
g.h.Cu=function(a){var b=2==a&&401==this.g.Le;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.jp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Av=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Du=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),n7(this.g)):this.N("handlerMessage",new Fqa(a[0],a[1]))};
g.h.nM=function(){this.i.isActive();var a=this.g,b=0;a.Vb&&b++;a.Bd&&b++;0==b&&this.connect(this.u,this.o)};G7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.u=function(a){a(Error("request timed out"))};var Lqa=(0,g.D)(),L7=null,P7=Array(50),O7=-1,Q7=!1;g.Sa(R7,g.N);R7.prototype.Md=function(){return this.g};
R7.prototype.contains=function(a){return!!l6(this.g,a)};
R7.prototype.get=function(a){return a?m6(this.g,a):null};
R7.prototype.info=function(a){N7(this.C,a)};g.t(T7,g.N);g.h=T7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.jB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.bq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.jB=function(){this.Aa=NaN;this.g=g.Xq(H7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.kN,this),onError:(0,g.x)(this.jN,this),ke:(0,g.x)(this.lN,this)})};
g.h.kN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new e6(c))};
g.h.jN=function(a){this.g=null;a.status&&404==a.status?this.i>=Tra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Tra[this.i],this.Aa=g.$p((0,g.x)(this.jB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.lN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var Tra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(V7,R7);g.h=V7.prototype;g.h.start=function(){U7(this)&&this.N("screenChange");!g.Ct("yt-remote-lounge-token-expiration")&&Oqa(this);g.bq(this.i);this.i=g.$p((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){U7(this);S7(this,a);W7(this,!1);this.N("screenChange");b(a);a.token||Oqa(this)};
g.h.remove=function(a,b){var c=U7(this);Nqa(this,a)&&(W7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.oo=function(a,b,c,d){var e=U7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,W7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.bq(this.i);V7.Za.U.call(this)};
g.h.zD=function(a){U7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}W7(this,!b);b&&N7(this.C,"Missed "+b+" lounge tokens.")};
g.h.yD=function(a){N7(this.C,"Requesting lounge tokens failed: "+a)};g.t(Y7,g.N);g.h=Y7.prototype;g.h.start=function(){var a=parseInt(g.Ct("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?$7(this):(this.o=(0,g.D)()+3E5,g.Bt("yt-remote-fast-check-period",this.o),this.es())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){X7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!m6(a,d)},this);
Z7(this,b)};
g.h.U=function(){g.bq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.es=function(){g.bq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Rqa(this);if(Z5(a)){var b=H7(this.u,"/pairing/get_screen_availability");this.i=I7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.QK,this,a),(0,g.x)(this.PK,this))}else Z7(this,{}),$7(this)};
g.h.QK=function(a,b){this.i=null;var c=g.Rb(Rqa(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Z7(this,d);$7(this)}else this.Gb("Changing Screen set during request."),this.es()};
g.h.PK=function(a){this.Gb("Screen availability failed: "+a);this.i=null;$7(this)};
g.h.Gb=function(a){N7("OnlineScreenService",a)};g.Sa(a8,R7);g.h=a8.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.oo=function(a,b,c,d){this.l.contains(a)?this.l.oo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,N7(this.C,a),d(Error(a)))};
g.h.Md=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.kB=function(){return(0,g.Xd)(this.Md(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.lB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new T7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.rf(f);d(b8(this,k))},this));
f.subscribe("pairingFailed",function(k){g.rf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.nN=function(a,b,c,d){g.Xq(H7(this.A,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Vqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Vqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(b8(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ke:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.rf(this.l);g.rf(this.i);a8.Za.U.call(this)};
g.h.HD=function(){Wqa(this);this.N("screenChange");this.i.update()};
a8.prototype.dispose=a8.prototype.dispose;g.Sa(d8,g.N);g.h=d8.prototype;g.h.En=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Qd=function(a){this.ea()||(a&&e8(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){N7(this.R,a)};
g.h.nB=function(){return null};
g.h.ws=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){e8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.ws("");d8.Za.U.call(this)};g.Sa(f8,d8);g.h=f8.prototype;g.h.us=function(a){if(this.g){if(this.g==a)return;e8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Yqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.Lg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Qd()},this),(0,g.x)(function(){this.Qd(Error("Failed to stop receiver app."))},this)):this.Qd(Error("Stopping cast device witout session."))};
g.h.ws=g.Ha;g.h.U=function(){this.info("disposeInternal");g.bq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;f8.Za.U.call(this)};
g.h.PL=function(a,b){if(!this.ea())if(b){var c=a6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lg(c));switch(d){case "mdxSessionStatus":Xqa(this,c.screenId);break;default:e8(this,"Unknown youtube message: "+d)}}else e8(this,"Unable to parse message.")}else e8(this,"No data in message.")};
g.h.Pv=function(a,b,c,d){Uqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(e8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$p((0,g.x)(this.Pv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nB=function(){return this.g};
g.h.pN=function(a){this.ea()||a||(e8(this,"Cast session died."),this.Qd())};g.Sa(g8,d8);g.h=g8.prototype;g.h.us=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.li=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ha;g.bq(this.A);this.o?this.o.stop((0,g.x)(this.Qd,this,null),(0,g.x)(this.Qd,this,"Failed to stop DIAL device.")):this.Qd()};
g.h.U=function(){this.g();this.g=g.Ha;g.bq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;g8.Za.U.call(this)};
g.h.sN=function(a){this.ea()||a||(e8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Qd())};
g.h.nq=function(a){this.H=k6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,$qa(this));a(b);Zqa(this)}else this.C=(0,g.x)(function(){g.bq(this.A);this.C=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,$qa(this));a(c);Zqa(this)},this),this.A=g.$p((0,g.x)(function(){this.C()},this),100)};
g.h.cE=function(a,b,c){Uqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.En(d),b(new chrome.cast.DialLaunchResponse(!1))):this.nq(b,c)},this),(0,g.x)(function(d){e8(this,"Failed to get DIAL screen: "+d);
this.nq(b,c)},this))};g.Sa(h8,d8);h8.prototype.stop=function(){this.Qd()};
h8.prototype.us=g.Ha;h8.prototype.li=function(){g.bq(this.g);this.g=NaN;var a=m6(this.F.Md(),this.i.label);a?this.En(a):this.Qd(Error("No such screen"))};
h8.prototype.U=function(){g.bq(this.g);this.g=NaN;h8.Za.U.call(this)};g.Sa(i8,g.N);g.h=i8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.az,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.NI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),Iqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.mB,this)),this.l=bra(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Gb("Failed to set initial custom receivers: "+g.Lg(k))},this)),this.N("yt-remote-cast2-availability-change",k8(this)),b(!0))},this),(0,g.x)(function(k){this.Gb("Failed to initialize API: "+g.Lg(k));
b(!1)},this))};
g.h.wM=function(a,b){j8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)j8("Unsetting old screen status: "+this.g.i.friendlyName),l8(this,null)}if(a&&b){if(!this.g){c=m6(this.i.Md(),a);if(!c){j8("setConnectedScreenStatus: Unknown screen.");return}var d=ara(this,c);d||(j8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Gb("Failed to set initial custom receivers: "+g.Lg(e))},this)));
j8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);l8(this,new h8(this.i,d),!0)}this.g.ws(b)}else j8("setConnectedScreenStatus: no screen.")};
g.h.xM=function(a){this.ea()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Gb("Setting connection data without a session")};
g.h.rN=function(){this.ea()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),l8(this,null)):j8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.az,this),(0,g.x)(this.VK,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.mB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],J7);g.rf(this.g);i8.Za.U.call(this)};
g.h.Gb=function(a){N7("Controller",a)};
g.h.bz=function(a,b){this.g==a&&(b||l8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.vK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),j8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)j8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{j8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:l8(this,
new h8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:l8(this,new g8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:l8(this,new f8(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.NI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return j8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);l8(this,new g8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.cE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.nq,b))};
g.h.az=function(a){if(!this.ea()){j8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)j8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),l8(this,new f8(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=m6(this.i.Md(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(j8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.rf(this.g),this.g=new f8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.bz,this,this.g)),this.g.li(null));this.g.us(a)}}};
g.h.qN=function(){return this.g?this.g.nB():null};
g.h.VK=function(a){this.ea()||(this.Gb("Failed to estabilish a session: "+g.Lg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&l8(this,null))};
g.h.zK=function(a){j8("Receiver availability updated: "+a);if(!this.ea()){var b=k8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;k8(this)!=b&&this.N("yt-remote-cast2-availability-change",k8(this))}};
g.h.mB=function(){this.ea()||(this.l=bra(this),j8("Updating custom receivers: "+g.Lg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Gb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",k8(this)))};
i8.prototype.setLaunchParams=i8.prototype.xM;i8.prototype.setConnectedScreenStatus=i8.prototype.wM;i8.prototype.stopSession=i8.prototype.rN;i8.prototype.getCastSession=i8.prototype.qN;i8.prototype.requestSession=i8.prototype.requestSession;i8.prototype.init=i8.prototype.init;i8.prototype.dispose=i8.prototype.dispose;var r8=[];w8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";x8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Me=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
w8.prototype.isAdPlaying=function(){return 1081==this.playerState};
w8.prototype.getDuration=function(){return this.u?this.D+y8(this):this.D};
w8.prototype.clone=function(){return new w8(C8(this))};g.t(E8,g.N);g.h=E8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,K8(this,"play")):J8(this,"play"),I8(this,1,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,K8(this,"pause")):J8(this,"pause"),I8(this,2,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=F8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.N("remotePlayerChange")}else G8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,K8(this,"stopVideo")):J8(this,"stopVideo");var a=F8(this);a.index=-1;a.videoId="";x8(a);H8(this,a);this.N("remotePlayerChange")}else G8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=F8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){N7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){N7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Qa(this.setVolume,a,b))};
g.h.lA=function(a,b){if(1==this.g){var c=F8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lg(b.style),g.ec(d,c.g));J8(this,"setSubtitlesTrack",d);H8(this,c)}else G8(this,g.Qa(this.lA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();J8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=F8(this);d.audioTrackId=c;H8(this,d)}else G8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=F8(this);c=c||0;var m={videoId:a,currentIndex:c};B8(l,a,c);g.Ca(b)&&(z8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Lg(k));J8(this,"setPlaylist",m);d||H8(this,l)};
g.h.Kn=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Qa(this.Kn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Qa(this.nextVideo,a,b))};
g.h.bv=function(){1==this.g?J8(this,"dismissAutoplay"):G8(this,this.bv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){ora(this);this.o=null;this.u.clear();D8(this,null);g.N.prototype.U.call(this)};
g.h.gt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sK=function(a,b){this.N(a,b)};
g.h.sI=function(a){if(!a)this.Ck(null),D8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=F8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)N7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.h.Ck=function(a){N7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),pra(this),this.N("remotePlayerChange")};
g.h.rI=function(a){a?(pra(this),this.N("remotePlayerChange")):this.Ck(null)};
g.h.Ms=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.GI=function(){var a=lra();a&&D8(this,a)};
g.h.Gb=function(a){N7("CP",a)};g.t(L8,g.N);g.h=L8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;z8(this.Oa,m);this.o="UNSUPPORTED";M8("Connecting with setPlaylist and params: "+g.Lg(l));this.g.connect({method:"setPlaylist",
params:g.Lg(l)},a,t6())}else M8("Connecting without params"),this.g.connect({},a,t6());rra(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),N8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){O8(this);Q8(this);P8(this);g.bq(this.C);this.C=NaN;g.bq(this.D);this.D=NaN;this.l=null;g.gs(this.R);this.R.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.sD=function(){this.Mh(2)};
g.h.wI=function(){M8("Channel opened");this.I&&(this.I=!1,P8(this),this.H=g.$p((0,g.x)(function(){M8("Timing out waiting for a screen.");this.Mh(1)},this),15E3));
zqa(Gqa(this.g),this.M)};
g.h.tI=function(){M8("Channel closed");isNaN(this.u)?w6(!0):w6();this.dispose()};
g.h.uI=function(a){w6();isNaN(this.Hj())?(M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,M8("Channel error: "+a+" with reconnection in "+this.Hj()+" ms"),N8(this,2))};
g.h.vI=function(a){a.params?M8("Received: action="+a.action+", params="+g.Lg(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=a6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new d6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
ura(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
ura(this,!1);break;case "remoteConnected":var b=new d6(a6(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||oqa(this.i,b);
break;case "remoteDisconnected":b=new d6(a6(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":wra(this,a);break;case "nowPlaying":yra(this,a);break;case "onStateChange":xra(this,a);break;case "onAdStateChange":zra(this,a);break;case "onVolumeChanged":Ara(this,a);break;case "onSubtitlesTrackChanged":vra(this,a);break;case "nowAutoplaying":Bra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Cra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:M8("Unrecognized action: "+a.action)}};
g.h.kM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&R8(this,"getNowPlaying")}};
g.h.iD=function(){var a=3;this.ea()||(a=0,isNaN(this.Hj())?F7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Mh=function(a){M8("Disconnecting with "+a);O8(this);this.N("beforeDisconnect",a);1==a&&w6();E7(this.g,a);this.dispose()};
g.h.hD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),B8(a,this.l,a.index));return C8(a)};
g.h.yM=function(a){var b=new w8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.bq(this.C),this.C=g.$p((0,g.x)(this.kM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&A8(this.Oa)==A8(b)&&g.Lg(this.Oa.g)==g.Lg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.Nv=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Hj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.aD=function(){return this.o||"UNSUPPORTED"};
g.h.bD=function(){return this.A||""};
g.h.iN=function(){if(!isNaN(this.Hj())){var a=this.g.i;g.zo(a.g);a.start()}};
g.h.rM=function(a,b){R8(this,a,b);tra(this)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Kf;L8.prototype.getProxyState=L8.prototype.iD;L8.prototype.disconnect=L8.prototype.Mh;L8.prototype.getPlayerContextData=L8.prototype.hD;L8.prototype.setPlayerContextData=L8.prototype.yM;L8.prototype.getOtherConnectedRemoteId=L8.prototype.Nv;L8.prototype.getReconnectTimeout=L8.prototype.Hj;L8.prototype.getAutoplayMode=L8.prototype.aD;L8.prototype.getAutoplayVideoId=L8.prototype.bD;L8.prototype.reconnect=L8.prototype.iN;
L8.prototype.sendMessage=L8.prototype.rM;g.t(S8,R7);g.h=S8.prototype;g.h.Md=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.add=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.oo=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Uc.$_ubk(this.i[a]);this.i.length=0;this.Uc=null;R7.prototype.U.call(this)};
g.h.mN=function(){this.N("screenChange")};
g.h.XJ=function(){this.N("onlineScreenChange")};
a8.prototype.$_st=a8.prototype.start;a8.prototype.$_gspc=a8.prototype.nN;a8.prototype.$_gsppc=a8.prototype.lB;a8.prototype.$_c=a8.prototype.contains;a8.prototype.$_g=a8.prototype.get;a8.prototype.$_a=a8.prototype.add;a8.prototype.$_un=a8.prototype.oo;a8.prototype.$_r=a8.prototype.remove;a8.prototype.$_gs=a8.prototype.Md;a8.prototype.$_gos=a8.prototype.kB;a8.prototype.$_s=a8.prototype.subscribe;a8.prototype.$_ubk=a8.prototype.Kf;var k9=null,j9=!1,T8=null,U8=null,i9=null,Y8=[];g.t(l9,g.A);g.h=l9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Xy,this);this.g.unsubscribe("remotePlayerChange",this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.Fn,this);this.g.unsubscribe("autoplayUpNext",this.By,this);this.g.unsubscribe("previousNextChange",this.Uy,this);this.g.unsubscribe("nowAutoplaying",this.Qy,this);this.g.unsubscribe("autoplayDismissed",this.Ay,this);this.g=this.u=null};
g.h.xx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(!F8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==F8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Oj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();q9(this,0==c?void 0:c);break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.qI=function(a){this.I.oD(a)};
g.h.SM=function(a){this.xx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.yA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||p9(this,a)};
g.h.My=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=F8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.rJ=function(){g.Xb(this.C)||Ora(this,this.C);this.D=!1};
g.h.Xy=function(a,b){this.A.stop();2==b&&this.xA()};
g.h.Ek=function(){if(o9(this)){this.o.stop();var a=F8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Rm=1;break;case 1082:case 1083:this.u.Rm=0;break;default:this.u.Rm=-1}switch(a.playerState){case 1081:case 1:n9(this,new g.GC(8));this.wA();break;case 1085:case 3:n9(this,new g.GC(9));break;case 1083:case 0:n9(this,new g.GC(2));this.H.stop();m9(this,this.i.getVideoData().lengthSeconds);break;case 1084:n9(this,new g.GC(4));break;case 2:n9(this,new g.GC(4));m9(this,A8(a));
break;case -1:n9(this,new g.GC(64));break;case -1E3:n9(this,new g.GC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=F8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,Ora(this,a));a=F8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.YA()}else Nra(this)};
g.h.Uy=function(){this.i.N("mdxpreviousnextchange")};
g.h.Fn=function(){o9(this)||Nra(this)};
g.h.vC=function(){this.g.bv()};
g.h.By=function(a){a&&(a=g.Xq("/watch_queue_ajax",{method:"GET",rd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.xL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.xL=function(a,b){var c=new g.rB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Qy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Ay=function(){this.i.N("mdxautoplaycanceled")};
g.h.NF=function(a,b){-1==F8(this.g).playerState?q9(this,a):b&&this.g.seekTo(a)};
g.h.YA=function(){if(o9(this)){var a=F8(this.g);this.l.Ma(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.My)}};
g.h.wA=function(){this.o.stop();if(!this.g.ea()){var a=F8(this.g);1==a.playerState&&n9(this,new g.GC(8));m9(this,A8(a));this.o.start()}};
g.h.xA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(r9,g.W);r9.prototype.o=function(){c6("mdx-privacy-popup-cancel");this.l.hide()};
r9.prototype.A=function(){c6("mdx-privacy-popup-confirm");this.l.hide()};g.t(s9,g.W);s9.prototype.u=function(a){Qra(this,a.state)};g.t(t9,g.hU);t9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.tb(a,this.A,this),g.iU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.ue(this.A(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.A=function(a){return a.key};
t9.prototype.te=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
t9.prototype.Jc=function(a){g.hU.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.jb()};g.t(u9,g.bL);g.h=u9.prototype;
g.h.create=function(){Hra(g.Zy(g.X(this.player)));this.o.push(g.gq("yt-remote-before-disconnect",this.nI,this));this.o.push(g.gq("yt-remote-connection-change",this.AK,this));this.o.push(g.gq("yt-remote-receiver-availability-change",this.Vy,this));this.o.push(g.gq("yt-remote-auto-connect",this.yK,this));this.o.push(g.gq("yt-remote-receiver-resumed",this.xK,this));this.o.push(g.gq("mdx-privacy-popup-confirm",this.bM,this));this.o.push(g.gq("mdx-privacy-popup-cancel",this.aM,this));this.Vy()};
g.h.load=function(){this.player.cancelPlayback();g.bL.prototype.load.call(this);this.u=new l9(this,this.player,this.g);var a=(a=Mra())?a.currentTime:0;var b=h9()?new E8(c9(),void 0):null;0==a&&b&&(a=A8(F8(b)));0!=a&&this.Lc(a);Pra(this,this.mk,this.mk);g.hY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.sf(this.u,this.g);this.g=this.u=null;g.bL.prototype.unload.call(this);g.hY(this.player.app,5);v9(this)};
g.h.U=function(){g.hq(this.o);g.bL.prototype.U.call(this)};
g.h.af=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.xx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Rm};
g.h.kD=function(){return this.loaded?this.u.suggestion:null};
g.h.Me=function(){return this.g?F8(this.g).Me:!1};
g.h.hasNext=function(){return this.g?F8(this.g).hasNext:!1};
g.h.Lc=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=F8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+y8(a):a.l,isAtLiveHead:1>=(a.u?a.i+y8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+y8(a):a.i,seekableStart:0<a.o?a.o+
y8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Kn=function(){this.g&&this.g.Kn()};
g.h.nI=function(a){1==a&&(this.F=this.g?F8(this.g):null)};
g.h.AK=function(){var a=h9()?new E8(c9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.rf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,A8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Vy=function(){this.C=[this.i].concat(Jra());var a=d9()||this.i;w9(this,a);this.player.la("onMdxReceiversChange")};
g.h.VL=function(a){!this.D&&g.TD(a,8)&&(this.player.pauseVideo(),v9(this))};
g.h.yK=function(){var a=d9();w9(this,a)};
g.h.xK=function(){this.l=d9()};
g.h.bM=function(){this.D=!0;v9(this);j9=!1;k9&&f9(k9,1);k9=null};
g.h.aM=function(){this.D=!1;v9(this);w9(this,this.i);this.l=this.i;j9=!1;k9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.C;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?u8():w9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.C.length&&"cast-selector-receiver"==this.C[1].key?(b&&u8(),!0):!1}};
g.h.Ms=function(){this.g.Ms()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.xV.remote=u9;})(_yt_player);
